### ISSUE TITLE
duplicate a track

### ISSUE THREAD

**Issue by taylorbf** [kylestetz/lissajous#18]
First off, terrific terrific project. I've had a truly engaging and *fun* time jamming out on it.

I frequently find myself wanting to branch off a track into a new track. I.e. once I've done the work to make a synth sound the way I like, I want to duplicate it into a new variable and give it a new beat and note pattern.

Something like `t.dup(v)` which would either duplicate t into a new track v, or vice versa.

I wonder if this is even a logistical possibility, or if there's a way to already accomplish this? This is totally a feature request though, and may be truly terrible to implement, in which case ignore this.

**Comment by kylestetz** [comment]
Sounds like a job for [`track.merge`](https://github.com/kylestetz/lissajous/blob/master/API.md#trackmergetracks)!

Cheers buddy :beers:
