### ISSUE TITLE
Compatibility grid

### ISSUE THREAD

**Issue by hughrawlinson** [kylestetz/lissajous#21]
Assuming progress on #4, it'd be great to automatically generate a compatibility grid with different browsers. Something like [this](https://github.com/substack/browser-badge) would work well, and there are [services](https://saucelabs.com/features#features-cross-browser) that run selenium tests that could be of use.

Particularly, the reason I see this being useful is that it allows contributors to quickly see cross-browser compatibility issues they could work on before issues are posted about them.

**Comment by hughrawlinson** [comment]
(the reason I thought of this is because wavs don't load in bufferLoader in Firefox (latest) running in Ubuntu 15.04, which I'm hoping to submit a PR for as soon as the next few weeks of conferences and business trips are done and I'm settled in nicely to my masters degree)

**Comment by kylestetz** [comment]
@hughrawlinson I'm at my limit this season for open source work, but I am 100% down with this idea and would support a pull request.

**Comment by hughrawlinson** [comment]
Lovely, I'll look into ways to do this then and try and submit a PR myself :)
