### ISSUE TITLE
Stop a track

### ISSUE THREAD

**Issue by mhdaouas** [kylestetz/lissajous#23]
How do we stop a playing track? `t.stop()` is not working for me, I get: `Uncaught TypeError: t.stop is not a function(…)`.

**Comment by mhdaouas** [comment]
OK, I found a workaround with `t.beat(0)`.

**Comment by kylestetz** [comment]
You got it— calling `beat()` with no arguments is the accepted way to do this. If you haven't checked it out yet, there's a [comprehensive tutorial](https://github.com/kylestetz/lissajous/blob/master/Tutorial.md) that will help you get the most out of lissajous. Thanks for checking out the project!
